# Generated by Django 3.1.6 on 2021-02-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
