# Generated by Django 3.1.6 on 2021-02-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210208_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('priority',)},
        ),
    ]
