# Generated by Django 3.1.6 on 2021-02-01 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_remove_partner_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='partners', to='partner.partner'),
        ),
    ]
