# Generated by Django 3.1.6 on 2021-02-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partner_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('to_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='partner.partner')),
            ],
        ),
    ]
