# Generated by Django 3.1.6 on 2021-02-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='to_grand_partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grand_actions', to='partner.partner'),
        ),
    ]
