# Generated by Django 3.1.6 on 2021-02-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-date',)},
        ),
    ]
