# Generated by Django 3.1.6 on 2021-02-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20210208_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('following', 'Уникальный переход по ссылке'), ('partner_pay', 'Оплата по ссылке'), ('grandpartner_pay', 'Оплата от партнера')], default='following', max_length=62),
        ),
    ]
